### ISSUE TITLE
Vilka platser skall ha länk Wkipedia i steg 1

### ISSUE THREAD

**Issue by salgo60** [salgo60/WikidataBygdeband#2]
Underlag till den lista vi skapar med koppling WIkipedia. Idag kopplas inte alltid Bygdeband distrikt till Wikipedia distrikt etc. så detta måste städas

**Status 20201017 Wikipedia**
[X] Distrikt --> Hembygdsportalen distrikt
[X] Socknar --> Hembygdsportalen distrikt
[] Församlingar

**Status 20201017 [Hembygdsportalen](https://www.hembygd.se/shf)**
[X] Distrikt --> Wikipedia distrikt
[] Socknar --> Hembygdsportalen distrikt
[] Församlingar

see också #3 

Stängs då vi inte har mer aktiviteter på G

**Comment by bjwela** [comment]
Idag så har vi endast län, kommun och distrikt länkade från början. Samma sak här om det går att få ut en lista på wikipedia id:n ifrån wikidata för alla län, kommuner och distrikt så kan jag enkelt länka om alla som är fel. 

Nästa steg skulle vara att göra samma sak för församlingar. 

För övriga platser har vi en sökfunktion som söker på wikipedia artiklar och då är det upp till redaktören för platsen att välja rätt artikel i wikipedia att länka.

**Comment by salgo60** [comment]
Gjorde en prototype för att testa hur sökning via API till Wikipedia fungerar för församling / distrikt / socken jmf med idag då man hoppar direkt till en Wikipedia artikel

- https://minancestry.blogspot.com/2020/04/testa-soka-fram-wikipedia-artiklar.html
- https://www.youtube.com/watch?v=xcjWPmJdIhk

**Comment by salgo60** [comment]
Stängs då vi inte har mer aktiviteter på G
