### ISSUE TITLE
Församlingar känns som många är inkopplade på fel ställe i Bygdeband. Hur vill Bygdeband ha det ex. Vallda församling Göteborg heter 440232 och finns under Borgholms kommun

### ISSUE THREAD

**Issue by salgo60** [salgo60/WikidataBygdeband#6]
https://www.hembygd.se/shf/plats/440232;type=list

Skall detta städas med Wikidata? Om ja bestäm hur ni vill ha det så ser vi vad vi behöver koppla ihop med Wikidata

**Comment by bjwela** [comment]
Går det att få ut en lista ifrån wikidata som mappar församling -> distrikt? Då skulle det vara ganska enkelt för mig att skriva ett skript som flyttar alla församlingar som ligger fel i Bygdeband.

**Comment by salgo60** [comment]
@bjwela kan vi starta med att ni skickar en lista till oss med 
* kommuner
* distrikt
* församlingar

CSV eller JSON

där det finns 
* namn
* Bygdeband ID
* ev. länk WIkipedia
* hur det är inkopplad idag så vi enklare kan match ex. Torsåkers församling [1861](https://www.hembygd.se/shf/plats/1861;type=list) --> Sverige / Gävleborgs län / Hofors kommun

1) med den listan matchar vi Wikidata 
2) vi skapar en lista med kopplingar, namn med korrekt Genetiv S, korrekt länk Wikipedia

Hlsn
Magnus
0705937579

**Comment by bjwela** [comment]
Jag har skrivit en liten funktion som söker ut distriktet för en församling baserat på om koordinaten ligger inom geojson polygonen för ett distrikt. Då kan jag mappa om detta automatiskt. Jag tror jag borde få 90% rätt då i alla fall. 

Källor till fel efter detta kan fortfarande vara: Att det finns några församlingar som saknar koordinater eller har felaktiga koordinater. 
Om församlingens koordinat ligger precis på en distriktsgräns.
Finns vissa distrikt som inte har helt sammanhängande gränser,  öar eller att det väver i varandra så att min algoritm inte klarar att hitta rätt.  

Jag tänkte köra igenom detta på test i eftermiddag, sedan kan jag ta ut en csv fil på de nya mappade församlingarna och jämföra med wikidata.

**Comment by salgo60** [comment]
@bjwela Bra ring gärna så vi kan stämma av några grejer 070-5937579

annars har du närhetssök också i Wikidata... ex. hitta alla distrikt i Wikidata 100 km från WD [Q33109113](https://www.wikidata.org/wiki/Q33109113?uselang=sv) Viggeby

* [karta 100km från Viggeby](https://w.wiki/MGk)
* [kod](https://w.wiki/MGn)

![image](https://user-images.githubusercontent.com/14206509/78690689-14898200-78f8-11ea-9159-beb0fdc92966.png)

![image](https://user-images.githubusercontent.com/14206509/78690383-a5ac2900-78f7-11ea-9a82-c6b2c489d4a5.png)

**Comment by bjwela** [comment]
[BygdebandPlatsIdnRev1.xlsx](https://github.com/salgo60/WikidataBygdeband/files/4448692/BygdebandPlatsIdnRev1.xlsx)

**Comment by bjwela** [comment]
[BygdebandPlatsIdnRev2.xlsx](https://github.com/salgo60/WikidataBygdeband/files/4515365/BygdebandPlatsIdnRev2.xlsx)

**Comment by salgo60** [comment]
@bjwela 
[BygdebandDistrikt_0_0_1](https://github.com/salgo60/WikidataBygdeband/blob/master/Data/BygdebandDistrikt_0_0_1.txt) filen [raw](https://raw.githubusercontent.com/salgo60/WikidataBygdeband/master/Data/BygdebandDistrikt_0_0_1.txt)

**Innehåller för Sveriges Distrikt**
BygdebandsID | Wikidata Qnummer |  curid eller pageid |  namn | BygdebandURL | WIkidata URL

 See [video](https://youtu.be/Zno9C5xR2UQ) 

![image](https://user-images.githubusercontent.com/14206509/81412982-f7d5a980-9144-11ea-9d11-db8df28657e8.png)

kod [gist.github](https://gist.github.com/salgo60/95897037ef342a29942492d309d13f27)

**Comment by salgo60** [comment]
@bjwela FYI du kan länka svWikipedia på Qnummer

exempel
* Bygdeband id [1100](https://www.hembygd.se/shf/plats/1100) = Solberga distrikt
  * Wikipedia [Solberga_distrikt,_Skåne](https://sv.wikipedia.org/wiki/Solberga_distrikt,_Sk%C3%A5ne) som har 
     * curid/pageid = 5087816 --> https://sv.wikipedia.org/?curid=5087816
     * Wikidata =  Q21560339 --> https://www.wikidata.org/wiki/Special:GoToLinkedPage/svwiki/Q21560339

dvs. du kan ange target med exempelvis svwiki 

* Bygdeband id [192](https://www.hembygd.se/shf/plats/192) = Hammarö kommun
  * Wikipedia [Hammarö kommun](url)
    * pageid/curid 45695 --> https://sv.wikipedia.org/?curid=45695
    * WIkidata Q499359 -->  https://www.wikidata.org/wiki/Special:GoToLinkedPage/svwiki/Q499359

men eftersom Hammarö kommun har artikel på 33 språk kan man hoppa direkt till dom genom att ändra "target"
* amwiki --> https://www.wikidata.org/wiki/Special:GoToLinkedPage/amwiki/Q499359
* bgqiki --> https://www.wikidata.org/wiki/Special:GoToLinkedPage/bgwiki/Q499359
* dewiki --> https://www.wikidata.org/wiki/Special:GoToLinkedPage/dewiki/Q499359
* ......

## Hämta Wikidata objektet via ett Bygdebandid 
* 192 -> [haswbstatement:P6192=192](https://www.wikidata.org/wiki/Special:Search?search=haswbstatement%3AP6192%3D192&fulltext=S%C3%B6k+efter+%27708%27&fulltext=Search&ns0=1&ns120=1  ) 

## Hämta alla Wikidata egenskaper kopplade till Bygdeband

* [downloadurl](https://query.wikidata.org/sparql?query=SELECT%20%3FBygdebandid%20%3Fid%20%3FidLabel%20%3FidDescription%20%3FWikiName%20WHERE%20%7B%0A%20%20%3Fid%20wdt%3AP6192%20%3FBygdebandid%20%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fid%3B%0A%20%20%20%20%20%20schema%3AinLanguage%20%22sv%22%3B%0A%20%20%20%20%20%20schema%3Aname%20%3FWikiName%3B%0A%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E.%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20(%3FidLabel)) -> gets a file with the reult
* [query](https://query.wikidata.org/#SELECT%20%3FBygdebandid%20%3Fid%20%3FidLabel%20%3FidDescription%20%3FWikiName%20WHERE%20%7B%0A%20%20%3Fid%20wdt%3AP6192%20%3FBygdebandid%20%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fid%3B%0A%20%20%20%20%20%20schema%3AinLanguage%20%22sv%22%3B%0A%20%20%20%20%20%20schema%3Aname%20%3FWikiName%3B%0A%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E.%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20(%3FidLabel))
  * [result query](https://w.wiki/QRY)

**Comment by salgo60** [comment]
Stänger denna då inga aktiviteter görs... skall mer göras ta kontakt med mig 0705937579 salgo60@msn.com
